version: '3.9'
services:
  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - hivemq

  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  hivemq:
    container_name: hivemq-broker
    image: hivemq/hivemq4:latest
    # hostname: localhost
    ports:
      - "8080:8080"
      - "1883:1883"
    # volumes:
    #   - logvolume01:/var/log
    # environment:
    #   HIVEMQ_BIND_ADDRESS: "0.0.0.0"

